# Generated by Django 3.2.9 on 2021-11-25 04:28

import django.utils.timezone
from django.db import migrations, models


def create_city(apps, edit_schema):
    city_model = apps.get_model('city', 'CityModel')
    city_model.objects.create(city_name="Ahemedabad", state_id=1)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.statemodel')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.RunPython(create_city)
    ]
