# Generated by Django 3.2.9 on 2021-11-25 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.statemodel')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
