# Generated by Django 3.2.9 on 2021-12-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citymodel',
            old_name='city_id',
            new_name='cityId',
        ),
        migrations.RenameField(
            model_name='citymodel',
            old_name='city_name',
            new_name='cityName',
        ),
        migrations.RenameField(
            model_name='citymodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='citymodel',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='state',
            field=models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, to='state.statemodel'),
        ),
    ]
