# Generated by Django 3.2.9 on 2021-12-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_auto_20211228_1343'),
        ('city', '0002_auto_20211226_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citymodel',
            old_name='cityId',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='citymodel',
            old_name='cityName',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='citymodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='citymodel',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='citymodel',
            name='create_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.statemodel'),
        ),
    ]
