# Generated by Django 3.2.9 on 2021-12-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20211228_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citymodel',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
