# Generated by Django 3.2.9 on 2022-02-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taluka', '0001_initial'),
        ('city', '0004_rename_create_by_citymodel_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citymodel',
            name='state',
        ),
        migrations.AddField(
            model_name='citymodel',
            name='taluka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taluka.talukamodel'),
        ),
    ]
