# Generated by Django 3.2.9 on 2022-02-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0001_initial'),
        ('patient_ovulation_profile', '0002_auto_20220207_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientovulationprofilemodel',
            name='patient_opd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel'),
        ),
    ]
