# Generated by Django 3.2.9 on 2022-02-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ovulation_profile', '0003_alter_patientovulationprofilemodel_patient_opd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientovulationprofilemodel',
            old_name='day',
            new_name='op_day',
        ),
    ]
