# Generated by Django 3.2.9 on 2022-03-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ovulation_profile', '0004_rename_day_patientovulationprofilemodel_op_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientovulationprofilemodel',
            name='endometrium_mm',
            field=models.CharField(default='', max_length=15),
        ),
    ]
