# Generated by Django 3.2.9 on 2022-05-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ovulation_profile', '0005_alter_patientovulationprofilemodel_endometrium_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientovulationprofilemodel',
            name='op_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
