# Generated by Django 3.2.9 on 2022-06-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ovulation_profile', '0006_patientovulationprofilemodel_op_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientovulationprofilemodel',
            name='endometrium_mm',
            field=models.FloatField(default=0.0),
        ),
    ]
