# Generated by Django 3.2.9 on 2022-01-10 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdviseModel',
            fields=[
                ('advise_id', models.AutoField(primary_key=True, serialize=False)),
                ('advise', models.TextField(null=True)),
                ('advise_for', models.CharField(choices=[('OPD', 'OPD'), ('SONOGRAPHY', 'SONOGRAPHY'), ('GENERAL', 'GENERAL')], default='OPD', max_length=15)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'advise',
            },
        ),
    ]
