# Generated by Django 3.2.9 on 2022-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisemodel',
            name='detail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='advisemodel',
            name='advise_for',
            field=models.CharField(choices=[('OPD', 'OPD'), ('SONOGRAPHY', 'SONOGRAPHY'), ('GENERAL', 'GENERAL'), ('POST-CS', 'POST-CS'), ('PRE-CS', 'PRE-CS')], default='OPD', max_length=15),
        ),
    ]
