# Generated by Django 3.2.9 on 2022-01-25 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0004_remove_patientmodel_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOpdModel',
            fields=[
                ('patient_opd_id', models.AutoField(primary_key=True, serialize=False)),
                ('opd_date', models.DateField(default=django.utils.timezone.now)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
            ],
            options={
                'db_table': 'patient_opd',
            },
        ),
    ]
