# Generated by Django 3.2.9 on 2022-02-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientopdmodel',
            name='patient_type',
            field=models.CharField(choices=[('OB', 'OB'), ('GYN', 'GYN')], default='OB', max_length=5),
        ),
        migrations.AddField(
            model_name='patientopdmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
