# Generated by Django 3.2.9 on 2022-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0002_auto_20220227_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientopdmodel',
            name='patient_type',
            field=models.CharField(choices=[('OB', 'OB'), ('GYN', 'GYN')], default='OB', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientopdmodel',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
