# Generated by Django 3.2.9 on 2022-03-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0003_auto_20220227_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientopdmodel',
            name='opd_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
