# Generated by Django 3.2.9 on 2022-06-22 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_opd', '0006_alter_patientopdmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientopdmodel',
            name='consulted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='consulted_by_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
