# Generated by Django 3.2.9 on 2022-07-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0007_patientopdmodel_consulted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientopdmodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
