# Generated by Django 3.2.9 on 2022-07-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0008_patientopdmodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientopdmodel',
            name='status',
            field=models.CharField(default='opd', max_length=25, null=True),
        ),
    ]
