# Generated by Django 3.2.9 on 2022-01-27 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0004_remove_patientmodel_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDeliveryModel',
            fields=[
                ('patient_delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('baby_no', models.CharField(default='', max_length=100)),
                ('sr_no', models.CharField(default='', max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('birth_time', models.CharField(max_length=10, null=True)),
                ('child_name', models.CharField(default='', max_length=100)),
                ('child_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10)),
                ('delivery_type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('CESARIAN', 'CESARIAN')], default='NORMAL', max_length=10)),
                ('religion', models.CharField(default='', max_length=25)),
                ('episio_by', models.CharField(default='', max_length=100)),
                ('dayan', models.CharField(default='', max_length=100)),
                ('village', models.CharField(default='', max_length=100)),
                ('taluka', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('pin', models.IntegerField(null=True)),
                ('marriage_age', models.IntegerField(default=0, null=True)),
                ('current_age', models.IntegerField(default=0, null=True)),
                ('weeks', models.IntegerField(default=0, null=True)),
                ('live_male_female', models.IntegerField(default=0, null=True)),
                ('no_of_delivery', models.IntegerField(default=0, null=True)),
                ('weight', models.FloatField(default=0.0, null=True)),
                ('father_eduction', models.CharField(default='', max_length=100)),
                ('mother_education', models.CharField(default='', max_length=100)),
                ('father_occupation', models.CharField(default='', max_length=250)),
                ('mother_occupation', models.CharField(default='', max_length=250)),
                ('baby_status', models.CharField(default='', max_length=15)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
            ],
            options={
                'db_table': 'patient_delivery',
            },
        ),
    ]
