# Generated by Django 3.2.9 on 2022-03-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='husband_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
