# Generated by Django 3.2.9 on 2022-04-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0002_patientdeliverymodel_husband_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='serial_no_month',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='serial_no_year',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='baby_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
