# Generated by Django 3.2.9 on 2022-06-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0004_rename_father_eduction_patientdeliverymodel_father_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='baby_no',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
