# Generated by Django 3.2.9 on 2022-06-06 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('taluka', '0001_initial'),
        ('city', '0005_auto_20220202_1058'),
        ('state', '0003_auto_20211228_1343'),
        ('patient_delivery', '0005_alter_patientdeliverymodel_baby_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdeliverymodel',
            name='village',
        ),
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='city.citymodel'),
        ),
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='husband_father_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='mother_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='state.statemodel'),
        ),
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='district.districtmodel'),
        ),
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='taluka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='taluka.talukamodel'),
        ),
    ]
