# Generated by Django 3.2.9 on 2022-06-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0006_auto_20220606_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='live_male_female',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
