# Generated by Django 3.2.9 on 2022-06-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0006_fieldmastermodel_slug'),
        ('patient_delivery', '0007_alter_patientdeliverymodel_live_male_female'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='dayan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_dayan', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='episio_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_dpisio_by', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='father_education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_f_education', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='mother_education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_m_education', to='manage_fields.managefieldsmodel'),
        ),
    ]
