# Generated by Django 3.2.9 on 2022-06-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0006_fieldmastermodel_slug'),
        ('patient_delivery', '0008_auto_20220610_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='father_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_f_occupation', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='mother_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_m_occupation', to='manage_fields.managefieldsmodel'),
        ),
    ]
