# Generated by Django 3.2.9 on 2022-06-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0009_auto_20220611_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='sr_no',
            field=models.IntegerField(null=True),
        ),
    ]
