# Generated by Django 3.2.9 on 2022-06-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0010_alter_patientdeliverymodel_sr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='landmark',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
