# Generated by Django 3.2.9 on 2022-06-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0011_patientdeliverymodel_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
