# Generated by Django 3.2.9 on 2022-07-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0006_fieldmastermodel_slug'),
        ('patient_delivery', '0013_alter_patientdeliverymodel_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_religion', to='manage_fields.managefieldsmodel'),
        ),
    ]
