# Generated by Django 3.2.9 on 2022-07-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0014_alter_patientdeliverymodel_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='child_gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=10),
        ),
    ]
