# Generated by Django 3.2.9 on 2022-07-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0015_alter_patientdeliverymodel_child_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
