# Generated by Django 3.2.9 on 2022-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0016_patientdeliverymodel_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdeliverymodel',
            old_name='last_name',
            new_name='delivery_husband_father_name',
        ),
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='delivery_last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
