# Generated by Django 3.2.9 on 2022-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0017_auto_20220728_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdeliverymodel',
            name='patient_mobile',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
