# Generated by Django 3.2.9 on 2022-09-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0018_patientdeliverymodel_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='delivery_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('CEASERIAN', 'CEASERIAN'), ('INSTRUMENTAL', 'INSTRUMENTAL')], default='NORMAL', max_length=20),
        ),
    ]
