# Generated by Django 3.2.9 on 2023-03-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_delivery', '0019_alter_patientdeliverymodel_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='district',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='state',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='patientdeliverymodel',
            name='taluka',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
