# Generated by Django 3.2.9 on 2022-02-16 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advice', '0004_alter_advicemodel_detail'),
        ('patient', '0010_patientmodel_name_title'),
        ('diagnosis', '0005_diagnosismedicinemodel'),
        ('patient_opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIndoorModel',
            fields=[
                ('patient_indoor_id', models.AutoField(primary_key=True, serialize=False)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('indoor_case_number', models.CharField(default='', max_length=100)),
                ('indoor_date', models.DateField(null=True)),
                ('indoor_time', models.CharField(max_length=15, null=True)),
                ('complain', models.CharField(max_length=500, null=True)),
                ('temprature', models.FloatField(default=0.0, null=True)),
                ('pulse', models.FloatField(default=0.0, null=True)),
                ('bp', models.CharField(default='', max_length=25, null=True)),
                ('spo2', models.CharField(default='', max_length=15, null=True)),
                ('pallor', models.CharField(default='', max_length=25, null=True)),
                ('lcterus', models.CharField(default='', max_length=25, null=True)),
                ('oedema', models.CharField(default='', max_length=25, null=True)),
                ('rs', models.CharField(default='', max_length=25, null=True)),
                ('cvs', models.CharField(default='', max_length=25, null=True)),
                ('pa_gyn', models.CharField(default='', max_length=25, null=True)),
                ('pa_obs', models.CharField(default='', max_length=25, null=True)),
                ('ut_weeks', models.IntegerField(default=0, null=True)),
                ('eb_pp', models.CharField(default='', max_length=25, null=True)),
                ('fhs', models.CharField(default='', max_length=25, null=True)),
                ('ut', models.CharField(default='', max_length=25, null=True)),
                ('ps', models.CharField(default='', max_length=25, null=True)),
                ('pv', models.CharField(default='', max_length=25, null=True)),
                ('ut_contra', models.CharField(default='', max_length=25, null=True)),
                ('adm_date', models.DateField(null=True)),
                ('adm_time', models.CharField(default='', max_length=15, null=True)),
                ('oper_date', models.DateField(null=True)),
                ('oper_time', models.CharField(default='', max_length=15, null=True)),
                ('disch_date', models.DateField(null=True)),
                ('disch_time', models.CharField(default='', max_length=15, null=True)),
                ('operation', models.CharField(default='', max_length=50, null=True)),
                ('field_order', models.CharField(default='', max_length=25, null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnosis.diagnosismodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
                ('patient_opd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel')),
            ],
            options={
                'db_table': 'patient_indoor',
            },
        ),
        migrations.CreateModel(
            name='IndoorAdviceModel',
            fields=[
                ('indoor_advice_id', models.AutoField(primary_key=True, serialize=False)),
                ('advice_date', models.DateField(null=True)),
                ('advice_time', models.CharField(max_length=15, null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advice.advicemodel')),
                ('patient_indoor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_indoor.patientindoormodel')),
            ],
            options={
                'db_table': 'indoor_advice',
            },
        ),
    ]
