# Generated by Django 3.2.9 on 2022-03-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_indoor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindoormodel',
            name='temprature',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
