# Generated by Django 3.2.9 on 2022-03-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_indoor', '0003_auto_20220322_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indooradvicemodel',
            name='advice_date',
        ),
        migrations.RemoveField(
            model_name='indooradvicemodel',
            name='advice_time',
        ),
    ]
