# Generated by Django 3.2.9 on 2022-04-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_indoor', '0004_auto_20220329_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindoormodel',
            name='indoor_case_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
