# Generated by Django 3.2.9 on 2022-05-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_indoor', '0005_alter_patientindoormodel_indoor_case_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientindoormodel',
            name='field_order',
        ),
    ]
