# Generated by Django 3.2.9 on 2023-03-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_indoor', '0007_patientindoormodel_provisional_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientindoormodel',
            name='daistolic_bp',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
