# Generated by Django 3.2.9 on 2022-01-28 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0001_initial'),
        ('patient_referal', '0002_patientreferalmodel_patient_opd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreferalmodel',
            name='patient_opd',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel'),
        ),
    ]
