# Generated by Django 3.2.9 on 2022-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_referal', '0004_auto_20220302_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreferalmodel',
            name='indication',
        ),
        migrations.AddField(
            model_name='patientreferalmodel',
            name='indication',
            field=models.ManyToManyField(to='manage_fields.ManageFieldsModel'),
        ),
    ]
