# Generated by Django 3.2.9 on 2022-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_referal', '0005_auto_20220303_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreferalmodel',
            name='indication',
            field=models.ManyToManyField(blank=True, to='manage_fields.ManageFieldsModel'),
        ),
    ]
