# Generated by Django 3.2.9 on 2022-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_referal', '0006_alter_patientreferalmodel_indication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreferalmodel',
            name='indication',
        ),
        migrations.AddField(
            model_name='patientreferalmodel',
            name='indication',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
