# Generated by Django 3.2.9 on 2022-05-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0005_alter_managefieldsmodel_field_value'),
        ('patient_referal', '0007_auto_20220506_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreferalmodel',
            name='indication',
        ),
        migrations.AddField(
            model_name='patientreferalmodel',
            name='indication',
            field=models.ManyToManyField(blank=True, to='manage_fields.ManageFieldsModel'),
        ),
    ]
