# Generated by Django 3.2.9 on 2022-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_referal', '0009_alter_patientreferalmodel_patient_opd'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReferalIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'patient_referal_indication',
                'managed': False,
            },
        ),
    ]
