# Generated by Django 3.2.9 on 2022-05-25 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=50)),
                ('actual_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
    ]
