# Generated by Django 3.2.9 on 2022-05-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='actual_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
    ]
