# Generated by Django 3.2.9 on 2022-05-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionmodel',
            old_name='package_id',
            new_name='subscription_id',
        ),
        migrations.RenameField(
            model_name='subscriptionmodel',
            old_name='package_name',
            new_name='subscription_name',
        ),
    ]
