# Generated by Django 3.2.9 on 2022-05-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20220525_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='actual_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='sell_price',
            field=models.IntegerField(),
        ),
    ]
