# Generated by Django 3.2.9 on 2022-06-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20220530_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='subscription_name',
            field=models.CharField(max_length=100),
        ),
    ]
