# Generated by Django 3.2.9 on 2022-02-16 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surgical_item', '0007_auto_20220131_1919'),
        ('patient', '0010_patientmodel_name_title'),
        ('patient_opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVoucherModel',
            fields=[
                ('patient_voucher_id', models.AutoField(primary_key=True, serialize=False)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
                ('patient_opd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel')),
            ],
            options={
                'db_table': 'patient_voucher',
            },
        ),
        migrations.CreateModel(
            name='VoucherItemModel',
            fields=[
                ('voucher_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_voucher.patientvouchermodel')),
                ('surgical_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surgical_item.surgicalitemmodel')),
            ],
            options={
                'db_table': 'voucher_item',
            },
        ),
    ]
