# Generated by Django 3.2.9 on 2022-02-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvouchermodel',
            name='bill_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientvouchermodel',
            name='voucher_no',
            field=models.CharField(default='', max_length=25),
        ),
    ]
