# Generated by Django 3.2.9 on 2022-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_voucher', '0002_auto_20220216_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvouchermodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patientvouchermodel',
            name='voucher_type',
            field=models.CharField(default='S', max_length=2),
        ),
    ]
