# Generated by Django 3.2.9 on 2022-04-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_voucher', '0003_auto_20220411_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvouchermodel',
            name='voucher_no',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
