# Generated by Django 3.2.9 on 2022-07-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_voucher', '0004_alter_patientvouchermodel_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvouchermodel',
            name='voucher_type',
            field=models.CharField(choices=[('S', 'Surgical Item'), ('C', 'Consultation'), ('U', 'USG'), ('R', 'Room'), ('O', 'Operative'), ('M', 'Medicine'), ('N', 'Nursing'), ('E', 'Other')], default='S', max_length=2),
        ),
    ]
