# Generated by Django 3.2.9 on 2021-12-08 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageFieldsModel',
            fields=[
                ('mf_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(default='', max_length=50)),
                ('field_value', models.CharField(default='', max_length=150)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.languagemodel')),
            ],
            options={
                'db_table': 'manage_field',
            },
        ),
    ]
