# Generated by Django 3.2.9 on 2021-12-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20211226_1839'),
        ('manage_fields', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managefieldsmodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='managefieldsmodel',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='managefieldsmodel',
            old_name='field_name',
            new_name='fieldName',
        ),
        migrations.RenameField(
            model_name='managefieldsmodel',
            old_name='field_value',
            new_name='fieldValue',
        ),
        migrations.RenameField(
            model_name='managefieldsmodel',
            old_name='mf_id',
            new_name='mfId',
        ),
        migrations.AlterField(
            model_name='managefieldsmodel',
            name='language',
            field=models.ForeignKey(db_column='languageId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.languagemodel'),
        ),
    ]
