# Generated by Django 3.2.9 on 2022-01-17 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0003_auto_20211228_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMasterModel',
            fields=[
                ('field_master_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_master_name', models.CharField(default='', max_length=50)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'field_master',
            },
        ),
        migrations.RemoveField(
            model_name='managefieldsmodel',
            name='field_name',
        ),
        migrations.AddField(
            model_name='managefieldsmodel',
            name='field_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manage_fields.fieldmastermodel'),
        ),
    ]
