# Generated by Django 3.2.9 on 2021-12-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_languagemodel_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagemodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='languagemodel',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='languagemodel',
            old_name='language_id',
            new_name='languageId',
        ),
    ]
