# Generated by Django 3.2.9 on 2021-12-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20211226_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagemodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='languagemodel',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='languagemodel',
            old_name='languageId',
            new_name='language_id',
        ),
    ]
