# Generated by Django 3.2.9 on 2022-04-09 06:47

import django.utils.timezone
from django.db import migrations, models


def create_default_year(apps, edit_schema):
    year_model = apps.get_model('financial_year', 'FinancialYearModel')
    year_model.objects.create(financial_year="2022-23", start_date="2022-04-01", end_date="2023-03-31", created_by=1,
                              deleted=0)
    year_model.objects.create(financial_year="2023-24", start_date="2023-04-01", end_date="2024-03-31", created_by=1,
                              deleted=0)
    year_model.objects.create(financial_year="2024-25", start_date="2024-04-01", end_date="2025-03-31", created_by=1,
                              deleted=0)
    year_model.objects.create(financial_year="2025-26", start_date="2025-04-01", end_date="2026-03-31", created_by=1,
                              deleted=0)
    year_model.objects.create(financial_year="2026-27", start_date="2026-04-01", end_date="2027-03-31", created_by=1,
                              deleted=0)
    year_model.objects.create(financial_year="2027-28", start_date="2027-04-01", end_date="2028-03-31", created_by=1,
                              deleted=0)
    year_model.objects.create(financial_year="2028-29", start_date="2028-04-01", end_date="2029-03-31", created_by=1,
                              deleted=0)
    year_model.objects.create(financial_year="2029-30", start_date="2029-04-01", end_date="2030-03-31", created_by=1,
                              deleted=0)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYearModel',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('financial_year', models.CharField(default='', max_length=15)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'financial_year',
            },
        ),
        migrations.RunPython(create_default_year)
    ]
