# Generated by Django 3.2.9 on 2022-04-25 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obgyn_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObgynConfig',
            new_name='ObgynConfigModel',
        ),
    ]
