# Generated by Django 3.2.9 on 2022-05-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0005_alter_managefieldsmodel_field_value'),
        ('obgyn_config', '0003_alter_obgynconfigmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='obgynconfigmodel',
            name='field_master_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manage_fields.fieldmastermodel'),
        ),
    ]
