# Generated by Django 3.2.9 on 2022-05-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taluka', '0001_initial'),
        ('obgyn_config', '0004_obgynconfigmodel_field_master_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='obgynconfigmodel',
            name='taluka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taluka.talukamodel'),
        ),
    ]
