# Generated by Django 3.2.9 on 2022-05-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_auto_20220202_1058'),
        ('district', '0001_initial'),
        ('state', '0003_auto_20211228_1343'),
        ('obgyn_config', '0005_obgynconfigmodel_taluka'),
    ]

    operations = [
        migrations.AddField(
            model_name='obgynconfigmodel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.citymodel'),
        ),
        migrations.AddField(
            model_name='obgynconfigmodel',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='district.districtmodel'),
        ),
        migrations.AddField(
            model_name='obgynconfigmodel',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state.statemodel'),
        ),
    ]
