# Generated by Django 3.2.9 on 2022-05-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obgyn_config', '0006_auto_20220527_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obgynconfigmodel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='obgynconfigmodel',
            name='state',
        ),
    ]
