# Generated by Django 3.2.9 on 2022-05-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_auto_20211228_1343'),
        ('district', '0001_initial'),
        ('obgyn_config', '0007_auto_20220527_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='obgynconfigmodel',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='district.districtmodel'),
        ),
        migrations.AddField(
            model_name='obgynconfigmodel',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state.statemodel'),
        ),
    ]
