# Generated by Django 3.2.9 on 2022-05-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obgyn_config', '0008_auto_20220527_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='district',
            new_name='district_id',
        ),
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='state',
            new_name='state_id',
        ),
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='taluka',
            new_name='taluka_id',
        ),
    ]
