# Generated by Django 3.2.9 on 2022-05-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obgyn_config', '0009_auto_20220527_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='city_id',
            new_name='city',
        ),
    ]
