# Generated by Django 3.2.9 on 2022-05-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obgyn_config', '0010_rename_city_id_obgynconfigmodel_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='city',
            new_name='city_id',
        ),
    ]
