# Generated by Django 3.2.9 on 2022-05-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obgyn_config', '0011_rename_city_obgynconfigmodel_city_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='obgynconfigmodel',
            old_name='taluka_id',
            new_name='taluka',
        ),
    ]
