# Generated by Django 3.2.9 on 2022-06-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obgyn_config', '0015_alter_obgynconfigmodel_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='obgynconfigmodel',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
