# Generated by Django 3.2.9 on 2022-02-16 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0010_patientmodel_name_title'),
        ('patient_opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistolapModel',
            fields=[
                ('patient_histolap_id', models.AutoField(primary_key=True, serialize=False)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('admission_date', models.DateField(null=True)),
                ('procedure_name', models.CharField(max_length=100, null=True)),
                ('right_tube', models.CharField(max_length=50, null=True)),
                ('left_tube', models.CharField(max_length=50, null=True)),
                ('uterus', models.CharField(max_length=100, null=True)),
                ('pod', models.CharField(max_length=100, null=True)),
                ('endo_cavity', models.CharField(max_length=100, null=True)),
                ('cervical_canal', models.CharField(max_length=100, null=True)),
                ('discharge_date', models.DateField(null=True)),
                ('remark', models.TextField(null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
                ('patient_opd', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel')),
            ],
            options={
                'db_table': 'patient_histolap',
            },
        ),
    ]
