# Generated by Django 3.2.9 on 2022-03-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_histolap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistolapmodel',
            name='discharge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patienthistolapmodel',
            name='left_tube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_tube', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patienthistolapmodel',
            name='procedure_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure_name', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patienthistolapmodel',
            name='right_tube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_tube', to='manage_fields.managefieldsmodel'),
        ),
    ]
