# Generated by Django 3.2.9 on 2022-03-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_histolap', '0002_auto_20220302_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistolapmodel',
            name='discharge_date',
            field=models.DateField(null=True),
        ),
    ]
