# Generated by Django 3.2.9 on 2022-03-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_histolap', '0003_alter_patienthistolapmodel_discharge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistolapmodel',
            name='admission_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patienthistolapmodel',
            name='discharge_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
