# Generated by Django 3.2.9 on 2022-03-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_histolap', '0004_auto_20220314_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistolapmodel',
            name='procedure_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patienthistolapmodel',
            name='procedure_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
