# Generated by Django 3.2.9 on 2022-05-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0005_alter_managefieldsmodel_field_value'),
        ('patient_histolap', '0006_alter_patienthistolapmodel_procedure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistolapmodel',
            name='cervical_canal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cervical_canal', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patienthistolapmodel',
            name='endo_cavity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='endo_cavity', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patienthistolapmodel',
            name='pod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pod', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patienthistolapmodel',
            name='uterus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uterus', to='manage_fields.managefieldsmodel'),
        ),
    ]
