# Generated by Django 3.2.9 on 2021-12-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalItemModel',
            fields=[
                ('surgical_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(default='', max_length=150)),
                ('mrp', models.FloatField(default=0)),
                ('batch_number', models.CharField(default='', max_length=50)),
                ('mfg_date', models.DateField(default=django.utils.timezone.now)),
                ('exp_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surgical_item',
            },
        ),
    ]
