# Generated by Django 3.2.9 on 2021-12-07 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalItemGroupModel',
            fields=[
                ('si_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(default='', max_length=150)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('surgical_item', models.ManyToManyField(to='surgical_item.SurgicalItemModel')),
            ],
            options={
                'db_table': 'surgical_item_group',
            },
        ),
    ]
