# Generated by Django 3.2.9 on 2021-12-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_item', '0004_surgicalitemgroupmodel_surgical_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgicalitemgroupmodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='surgicalitemgroupmodel',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='surgicalitemgroupmodel',
            old_name='drugName',
            new_name='drug_name',
        ),
        migrations.RenameField(
            model_name='surgicalitemgroupmodel',
            old_name='siGroupId',
            new_name='si_group_id',
        ),
        migrations.RenameField(
            model_name='surgicalitemmodel',
            old_name='batchNumber',
            new_name='batch_number',
        ),
        migrations.RenameField(
            model_name='surgicalitemmodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='surgicalitemmodel',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='surgicalitemmodel',
            old_name='drugName',
            new_name='drug_name',
        ),
        migrations.RenameField(
            model_name='surgicalitemmodel',
            old_name='expDate',
            new_name='exp_date',
        ),
        migrations.RenameField(
            model_name='surgicalitemmodel',
            old_name='mfgDate',
            new_name='mfg_date',
        ),
        migrations.RenameField(
            model_name='surgicalitemmodel',
            old_name='surgicalItemId',
            new_name='surgical_item_id',
        ),
    ]
