# Generated by Django 3.2.9 on 2022-01-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_item', '0005_auto_20211228_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgicalitemgroupmodel',
            old_name='drug_name',
            new_name='drug_group_name',
        ),
    ]
