# Generated by Django 3.2.9 on 2022-04-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_item', '0007_auto_20220131_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalitemgroupmodel',
            name='surgical_item',
            field=models.ManyToManyField(blank=True, to='surgical_item.SurgicalItemModel'),
        ),
    ]
