# Generated by Django 3.2.9 on 2022-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_item', '0008_alter_surgicalitemgroupmodel_surgical_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalItemGroupSurgicalItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surgicalitemgroupmodel_id', models.IntegerField()),
                ('surgicalitemmodel_id', models.IntegerField()),
            ],
            options={
                'db_table': 'surgical_item_group_surgical_item',
                'managed': False,
            },
        ),
    ]
