# Generated by Django 3.2.9 on 2022-01-31 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advice', '0004_alter_advicemodel_detail'),
        ('patient', '0007_rename_husband_name_patientmodel_husband_father_name'),
        ('diagnosis', '0005_diagnosismedicinemodel'),
        ('patient_opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDischargeModel',
            fields=[
                ('patient_discharge_id', models.AutoField(primary_key=True, serialize=False)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('admission_time', models.CharField(default='', max_length=15)),
                ('complain_of', models.CharField(default='', max_length=500)),
                ('name_of_operation', models.CharField(default='', max_length=100)),
                ('ot_date', models.DateField(default=django.utils.timezone.now)),
                ('ot_time', models.CharField(default='', max_length=15)),
                ('treatment_given', models.CharField(default='', max_length=250)),
                ('any_history', models.TextField(null=True)),
                ('assisted', models.CharField(default='', max_length=250)),
                ('discharge_date', models.DateField(default=django.utils.timezone.now)),
                ('discharge_time', models.CharField(default='', max_length=15)),
                ('remark', models.TextField(null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advice.advicemodel')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnosis.diagnosismodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
                ('patient_opd', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel')),
            ],
            options={
                'db_table': 'patient_discharge',
            },
        ),
    ]
