# Generated by Django 3.2.9 on 2022-03-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_discharge', '0002_alter_patientdischargemodel_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargemodel',
            name='advice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pd_advice', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patientdischargemodel',
            name='complain_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complain_of', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patientdischargemodel',
            name='name_of_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_of_operation', to='manage_fields.managefieldsmodel'),
        ),
    ]
