# Generated by Django 3.2.9 on 2022-07-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0006_fieldmastermodel_slug'),
        ('patient_discharge', '0005_alter_patientdischargemodel_patient_opd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargemodel',
            name='treatment_given',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='treatment_given', to='manage_fields.managefieldsmodel'),
        ),
    ]
