# Generated by Django 3.2.9 on 2022-01-11 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0012_auto_20211230_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='user.user')),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('married', models.BooleanField(default=False)),
                ('department', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD')], default='OPD', max_length=5)),
                ('patient_type', models.CharField(choices=[('OB', 'OB'), ('GYN', 'GYN')], default='OB', max_length=5)),
                ('patient_detail', models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL')], default='PARTIAL', max_length=8)),
                ('date_of_opd', models.DateTimeField(default=django.utils.timezone.now)),
                ('registered_no', models.CharField(default='', max_length=100)),
                ('grand_parent_name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('taluka', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'patient',
            },
            bases=('user.user',),
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
