# Generated by Django 3.2.9 on 2022-01-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientmodel_date_of_opd'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='pid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
