# Generated by Django 3.2.9 on 2022-01-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientmodel_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='pid',
        ),
    ]
