# Generated by Django 3.2.9 on 2022-01-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patientmodel_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='grand_parent_name',
            new_name='grand_father_name',
        ),
    ]
