# Generated by Django 3.2.9 on 2022-01-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_grand_parent_name_patientmodel_grand_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='husband_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
