# Generated by Django 3.2.9 on 2022-01-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientmodel_husband_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='husband_name',
            new_name='husband_father_name',
        ),
    ]
