# Generated by Django 3.2.9 on 2022-02-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_rename_husband_name_patientmodel_husband_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='profile_image',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
