# Generated by Django 3.2.9 on 2022-02-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patientmodel_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='taluka',
        ),
    ]
