# Generated by Django 3.2.9 on 2022-02-16 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient', '0009_auto_20220215_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='name_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_title', to='manage_fields.managefieldsmodel'),
        ),
    ]
