# Generated by Django 3.2.9 on 2022-02-17 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient', '0010_patientmodel_name_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='grand_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grand_title', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='husband_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='husband_title', to='manage_fields.managefieldsmodel'),
        ),
    ]
