# Generated by Django 3.2.9 on 2022-03-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20220217_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='religion',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
