# Generated by Django 3.2.9 on 2022-04-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_patientmodel_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='first_edd',
            field=models.DateField(null=True),
        ),
    ]
