# Generated by Django 3.2.9 on 2022-05-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20220506_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='mob_no_barcode',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='regd_no_barcode',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
