# Generated by Django 3.2.9 on 2022-06-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_auto_20220525_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER')], default='FEMALE', max_length=15),
        ),
    ]
