# Generated by Django 3.2.9 on 2022-06-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0006_fieldmastermodel_slug'),
        ('patient', '0016_patientmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='religion', to='manage_fields.managefieldsmodel'),
        ),
    ]
