# Generated by Django 3.2.9 on 2022-07-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_patientmodel_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='husband_father_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
