# Generated by Django 3.2.9 on 2022-07-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_auto_20220720_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='grand_father_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='husband_father_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
