# Generated by Django 3.2.9 on 2022-07-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_alter_patientmodel_grand_father_name'),
        ('patient', '0019_auto_20220720_1814'),
    ]

    operations = [
    ]
