# Generated by Django 3.2.9 on 2022-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_merge_20220721_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='age',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
