# Generated by Django 3.2.9 on 2022-01-28 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_opd', '0001_initial'),
        ('patient', '0007_rename_husband_name_patientmodel_husband_father_name'),
        ('diagnosis', '0005_diagnosismedicinemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientUSGFormModel',
            fields=[
                ('patient_usgform_id', models.AutoField(primary_key=True, serialize=False)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('ut_weeks', models.IntegerField(default=0)),
                ('lmp_date', models.DateField(null=True)),
                ('usg_image_no', models.CharField(max_length=250, null=True)),
                ('result_of_sonography', models.CharField(max_length=250, null=True)),
                ('serial_no_month', models.IntegerField(default=0)),
                ('serial_no_year', models.IntegerField(default=0)),
                ('ref_by_dr', models.CharField(default='', max_length=150)),
                ('village', models.CharField(default='', max_length=100)),
                ('taluka', models.CharField(default='', max_length=100)),
                ('doctor_center_taluka_distrcit', models.CharField(max_length=250, null=True)),
                ('any_other', models.CharField(max_length=150, null=True)),
                ('doctor_address', models.TextField(null=True)),
                ('name_of_doctor', models.CharField(max_length=150, null=True)),
                ('consent_obtained_date', models.DateField(default=django.utils.timezone.now)),
                ('procedure_date', models.DateField(default=django.utils.timezone.now)),
                ('result_of_diagnostic_conveyed_to', models.CharField(max_length=250, null=True)),
                ('sonography_date', models.DateField(default=django.utils.timezone.now)),
                ('any_indication_mtp', models.CharField(max_length=250, null=True)),
                ('mtp_done', models.CharField(max_length=100, null=True)),
                ('remark', models.TextField(null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnosis.diagnosismodel')),
                ('indication', models.ManyToManyField(to='manage_fields.ManageFieldsModel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
                ('patient_opd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel')),
            ],
            options={
                'db_table': 'patient_usgform',
            },
        ),
        migrations.CreateModel(
            name='USGFormChildModel',
            fields=[
                ('usgform_child_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10)),
                ('child_year', models.IntegerField(null=True)),
                ('child_month', models.IntegerField(null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_usgform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_usgform.patientusgformmodel')),
            ],
            options={
                'db_table': 'usgform_child',
            },
        ),
    ]
