# Generated by Django 3.2.9 on 2022-01-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientusgformmodel',
            old_name='doctor_center_taluka_distrcit',
            new_name='doctor_center_taluka_district',
        ),
    ]
