# Generated by Django 3.2.9 on 2022-01-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0001_initial'),
        ('patient_usgform', '0002_rename_doctor_center_taluka_distrcit_patientusgformmodel_doctor_center_taluka_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='patient_opd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel'),
        ),
    ]
