# Generated by Django 3.2.9 on 2022-03-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_usgform', '0003_alter_patientusgformmodel_patient_opd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='any_indication_mtp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='any_indication_mtp', to='manage_fields.managefieldsmodel'),
        ),
        migrations.RemoveField(
            model_name='patientusgformmodel',
            name='indication',
        ),
        migrations.AddField(
            model_name='patientusgformmodel',
            name='indication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='puf_indication', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='result_of_sonography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_of_sonography', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='usg_image_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
