# Generated by Django 3.2.9 on 2022-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgform', '0004_auto_20220302_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='usg_image_no',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
