# Generated by Django 3.2.9 on 2022-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgform', '0005_alter_patientusgformmodel_usg_image_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='taluka',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
