# Generated by Django 3.2.9 on 2022-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_usgform', '0006_alter_patientusgformmodel_taluka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientusgformmodel',
            name='indication',
        ),
        migrations.AddField(
            model_name='patientusgformmodel',
            name='indication',
            field=models.ManyToManyField(blank=True, to='manage_fields.ManageFieldsModel'),
        ),
    ]
