# Generated by Django 3.2.9 on 2022-04-25 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgform', '0007_auto_20220425_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='consent_obtained_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='procedure_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='ref_by_dr',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='serial_no_month',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='serial_no_year',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='sonography_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='village',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
