# Generated by Django 3.2.9 on 2022-04-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_usgform', '0008_auto_20220425_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='any_other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='any_other', to='manage_fields.managefieldsmodel'),
        ),
    ]
