# Generated by Django 3.2.9 on 2022-04-25 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_usgform', '0009_alter_patientusgformmodel_any_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='ref_by_dr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ref_by_dr', to=settings.AUTH_USER_MODEL),
        ),
    ]
