# Generated by Django 3.2.9 on 2022-04-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgform', '0010_alter_patientusgformmodel_ref_by_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='ref_by_dr',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
