# Generated by Django 3.2.9 on 2022-04-25 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_usgform', '0011_alter_patientusgformmodel_ref_by_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='name_of_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_of_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
