# Generated by Django 3.2.9 on 2022-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgform', '0012_alter_patientusgformmodel_name_of_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usgformchildmodel',
            name='child_month',
        ),
        migrations.RemoveField(
            model_name='usgformchildmodel',
            name='child_year',
        ),
        migrations.AddField(
            model_name='usgformchildmodel',
            name='child_dob',
            field=models.DateField(null=True),
        ),
    ]
