# Generated by Django 3.2.9 on 2022-05-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0010_alter_diagnosismodel_medicine'),
        ('patient_usgform', '0013_auto_20220506_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnosis.diagnosismodel'),
        ),
    ]
