# Generated by Django 3.2.9 on 2022-06-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgform', '0015_alter_patientusgformmodel_patient_opd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgformmodel',
            name='ut_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
