# Generated by Django 3.2.9 on 2022-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgform', '0016_alter_patientusgformmodel_ut_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientusgformmodel',
            name='live_male_female',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
