# Generated by Django 3.2.9 on 2021-12-02 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('medicine_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_type', models.CharField(default='', max_length=50)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'medicine_type',
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('timing_id', models.AutoField(primary_key=True, serialize=False)),
                ('timing', models.CharField(default='', max_length=25)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.languagemodel')),
            ],
            options={
                'db_table': 'timing',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(default='', max_length=20)),
                ('medicine', models.CharField(default='', max_length=250)),
                ('contain', models.CharField(default='', max_length=500)),
                ('per_day', models.IntegerField(default=0)),
                ('for_day', models.IntegerField(default=0)),
                ('total_tablet', models.IntegerField(default=0)),
                ('company', models.CharField(default='', max_length=250)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bed_timing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_timing', to='medicine.timing')),
                ('evening_timing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evening_timing', to='medicine.timing')),
                ('medicine_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.medicinetype')),
                ('morning_timing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morning_timing', to='medicine.timing')),
                ('noon_timing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noon_timing', to='medicine.timing')),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
