# Generated by Django 3.2.9 on 2021-12-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicine',
            new_name='MedicineModel',
        ),
        migrations.RenameModel(
            old_name='MedicineType',
            new_name='MedicineTypeModel',
        ),
        migrations.RenameModel(
            old_name='Timing',
            new_name='TimingModel',
        ),
    ]
