# Generated by Django 3.2.9 on 2021-12-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20211226_1839'),
        ('medicine', '0002_auto_20211207_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='for_day',
            new_name='forDay',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='medicine_id',
            new_name='medicineId',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='per_day',
            new_name='perDay',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='total_tablet',
            new_name='totalTablet',
        ),
        migrations.RenameField(
            model_name='medicinetypemodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='medicinetypemodel',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='medicinetypemodel',
            old_name='medicine_type',
            new_name='medicineType',
        ),
        migrations.RenameField(
            model_name='medicinetypemodel',
            old_name='medicine_type_id',
            new_name='medicineTypeId',
        ),
        migrations.RenameField(
            model_name='timingmodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='timingmodel',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='timingmodel',
            old_name='timing_id',
            new_name='timingId',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='bed_timing',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='evening_timing',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='medicine_type',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='morning_timing',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='noon_timing',
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='bedTiming',
            field=models.ForeignKey(db_column='bedTimingId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_timing', to='medicine.timingmodel'),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='eveningTiming',
            field=models.ForeignKey(db_column='eveningTimingId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evening_timing', to='medicine.timingmodel'),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='medicineType',
            field=models.ForeignKey(db_column='medicineTypeId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.medicinetypemodel'),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='morningTiming',
            field=models.ForeignKey(db_column='morningTimingId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morning_timing', to='medicine.timingmodel'),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='noonTiming',
            field=models.ForeignKey(db_column='noonTimingId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noon_timing', to='medicine.timingmodel'),
        ),
        migrations.AlterField(
            model_name='timingmodel',
            name='language',
            field=models.ForeignKey(db_column='languageId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.languagemodel'),
        ),
    ]
