# Generated by Django 3.2.9 on 2021-12-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_auto_20211228_1610'),
        ('medicine', '0003_auto_20211226_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='forDay',
            new_name='for_day',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='medicineId',
            new_name='medicine_id',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='medicineType',
            new_name='medicine_type',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='perDay',
            new_name='per_day',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='totalTablet',
            new_name='total_tablet',
        ),
        migrations.RenameField(
            model_name='medicinetypemodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='medicinetypemodel',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='medicinetypemodel',
            old_name='medicineType',
            new_name='medicine_type',
        ),
        migrations.RenameField(
            model_name='medicinetypemodel',
            old_name='medicineTypeId',
            new_name='medicine_type_id',
        ),
        migrations.RenameField(
            model_name='timingmodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='timingmodel',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='timingmodel',
            old_name='timingId',
            new_name='timing_id',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='bedTiming',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='eveningTiming',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='morningTiming',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='noonTiming',
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='bed_timing',
            field=models.ForeignKey(db_column='bed_timing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_timing', to='medicine.timingmodel'),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='evening_timing',
            field=models.ForeignKey(db_column='evening_timing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evening_timing', to='medicine.timingmodel'),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='morning_timing',
            field=models.ForeignKey(db_column='morning_timing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morning_timing', to='medicine.timingmodel'),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='noon_timing',
            field=models.ForeignKey(db_column='noon_timing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noon_timing', to='medicine.timingmodel'),
        ),
        migrations.AlterField(
            model_name='timingmodel',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.languagemodel'),
        ),
    ]
