# Generated by Django 3.2.9 on 2022-01-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20211228_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='medicine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.medicinetypemodel'),
        ),
    ]
