# Generated by Django 3.2.9 on 2022-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_alter_medicinemodel_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingmodel',
            name='timing',
            field=models.CharField(default='', max_length=100),
        ),
    ]
