# Generated by Django 3.2.9 on 2022-03-07 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0004_auto_20211228_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateHeaderModel',
            fields=[
                ('template_header_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_header_name', models.CharField(default='', max_length=35, null=True)),
                ('header_text', models.TextField(null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='language.languagemodel')),
            ],
            options={
                'db_table': 'template_header',
            },
        ),
    ]
