# Generated by Django 3.2.9 on 2022-05-25 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_purchaseModel',
            fields=[
                ('subscription_Purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('description', models.TextField(default='')),
                ('inactive', models.BooleanField(default=False)),
                ('tax_perc', models.FloatField(default=0)),
                ('invoice_no', models.IntegerField(default=0)),
                ('inv_year', models.CharField(default='', max_length=15)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='subscription.subscriptionmodel')),
            ],
        ),
    ]
