# Generated by Django 3.2.9 on 2022-05-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterModelTable(
            name='subscription_purchasemodel',
            table='subscription_purchase',
        ),
    ]
