# Generated by Django 3.2.9 on 2022-05-25 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0002_auto_20220525_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_purchasemodel',
            name='end_date',
        ),
        migrations.AddField(
            model_name='subscription_purchasemodel',
            name='over_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
