# Generated by Django 3.2.9 on 2022-05-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0004_auto_20220526_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_purchasemodel',
            old_name='subscription_Purchase_id',
            new_name='subscription_purchase_id',
        ),
    ]
