# Generated by Django 3.2.9 on 2022-06-08 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0005_rename_subscription_purchase_id_subscription_purchasemodel_subscription_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_purchasemodel',
            name='subscription_date',
        ),
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='over_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
