# Generated by Django 3.2.9 on 2022-06-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0006_auto_20220608_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_purchasemodel',
            name='tax_perc',
        ),
        migrations.AddField(
            model_name='subscription_purchasemodel',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription_purchasemodel',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription_purchasemodel',
            name='payment_id',
            field=models.IntegerField(default=0),
        ),
    ]
