# Generated by Django 3.2.9 on 2022-06-06 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0007_auto_20220606_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='subscription_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
