# Generated by Django 3.2.9 on 2022-06-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0007_auto_20220608_1420'),
        ('subscription_purchase', '0008_auto_20220606_1246'),
    ]

    operations = [
    ]
