# Generated by Django 3.2.9 on 2022-06-07 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20220530_1342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription_purchase', '0008_auto_20220606_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionmodel'),
        ),
    ]
