# Generated by Django 3.2.9 on 2022-06-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0009_merge_0007_auto_20220608_1420_0008_auto_20220606_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='over_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
