# Generated by Django 3.2.9 on 2022-06-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0010_auto_20220608_1740'),
        ('subscription_purchase', '0010_auto_20220609_1102'),
    ]

    operations = [
    ]
