# Generated by Django 3.2.9 on 2022-07-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_purchase', '0009_auto_20220607_1904'),
        ('subscription_purchase', '0011_merge_0010_auto_20220608_1740_0010_auto_20220609_1102'),
    ]

    operations = [
    ]
