# Generated by Django 3.2.9 on 2022-07-11 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0003_alter_subscriptionmodel_subscription_name'),
        ('subscription_purchase', '0012_merge_20220711_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription_purchasemodel',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscriptionmodel'),
        ),
    ]
