# Generated by Django 3.2.9 on 2022-01-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advicegroupmodel',
            name='advice',
        ),
        migrations.AddField(
            model_name='advicemodel',
            name='advice_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advice.advicegroupmodel'),
        ),
    ]
