# Generated by Django 3.2.9 on 2022-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0003_auto_20220118_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicemodel',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
