# Generated by Django 3.2.9 on 2022-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0005_alter_advicegroupmodel_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceGroupAdviceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('advicegroupmodel_id', models.IntegerField()),
                ('advicemodel_id', models.IntegerField()),
            ],
            options={
                'db_table': 'advice_group_advice',
                'managed': False,
            },
        ),
    ]
