# Generated by Django 3.2.9 on 2022-02-02 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0003_auto_20211228_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=50)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.statemodel')),
            ],
            options={
                'db_table': 'district',
            },
        ),
    ]
