# Generated by Django 3.2.9 on 2021-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('HOSPITAL', 'HOSPITAL'), ('STAFF', 'STAFF'), ('DOCTOR', 'DOCTOR')], default='DOCTOR', max_length=9),
            preserve_default=False,
        ),
    ]
