# Generated by Django 3.2.9 on 2021-12-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_languagemodel_code'),
        ('user', '0002_auto_20211125_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='language.languagemodel'),
        ),
    ]
