# Generated by Django 3.2.9 on 2021-12-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211226_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_code',
            new_name='userCode',
        ),
    ]
