# Generated by Django 3.2.9 on 2021-12-27 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20211226_1635'),
        ('state', '0002_auto_20211226_1845'),
        ('language', '0003_auto_20211226_1839'),
        ('user', '0006_auto_20211227_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='aadharCard',
            new_name='aadhar_card',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='faxNumber',
            new_name='fax_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hospitalName',
            new_name='hospital_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middleName',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='registrationNo',
            new_name='registration_no',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userType',
            new_name='user_Type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userCode',
            new_name='user_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='defaultLanguage',
        ),
        migrations.AddField(
            model_name='user',
            name='default_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='language.languagemodel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='city.citymodel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='state.statemodel'),
        ),
    ]
