# Generated by Django 3.2.9 on 2021-12-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211227_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_Type',
            new_name='user_type',
        ),
    ]
