# Generated by Django 3.2.9 on 2021-12-30 11:24

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
