# Generated by Django 3.2.9 on 2021-12-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify',
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
