# Generated by Django 3.2.9 on 2022-01-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20211230_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('HOSPITAL', 'HOSPITAL'), ('STAFF', 'STAFF'), ('DOCTOR', 'DOCTOR'), ('PATIENT', 'PATIENT')], max_length=9),
        ),
    ]
