# Generated by Django 3.2.9 on 2022-02-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('taluka', '0001_initial'),
        ('user', '0014_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='district.districtmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='taluka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='taluka.talukamodel'),
        ),
    ]
