# Generated by Django 3.2.9 on 2022-04-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220215_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operative_charge',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rs_per_day_nursing',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rs_per_room',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rs_per_usg',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rs_per_visit',
            field=models.FloatField(default=0, null=True),
        ),
    ]
