# Generated by Django 3.2.9 on 2022-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220425_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='landmark',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
