# Generated by Django 3.2.9 on 2022-02-16 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0010_patientmodel_name_title'),
        ('diagnosis', '0005_diagnosismedicinemodel'),
        ('patient_opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBillingModel',
            fields=[
                ('patient_billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('invoice_no', models.CharField(max_length=25, null=True)),
                ('admission_date', models.DateField(null=True)),
                ('ot_date', models.DateField(null=True)),
                ('discharge_date', models.DateField(null=True)),
                ('procedure_name', models.CharField(max_length=100, null=True)),
                ('no_of_visit', models.IntegerField(default=0)),
                ('rs_per_visit', models.FloatField(default=0.0)),
                ('consulting_fees', models.FloatField(default=0.0)),
                ('no_of_usg', models.IntegerField(default=0)),
                ('rs_per_usg', models.FloatField(default=0.0)),
                ('usg_rs', models.FloatField(default=0.0)),
                ('room_no_of_day', models.CharField(max_length=25, null=True)),
                ('rs_per_room', models.FloatField(default=0.0)),
                ('room_type', models.CharField(default='', max_length=25)),
                ('room_rs', models.FloatField(default=0.0)),
                ('operative_charge_rs', models.FloatField(default=0.0)),
                ('medicine_rs', models.FloatField(default=0.0)),
                ('nursing_no_of_days', models.IntegerField(default=0)),
                ('rs_per_day', models.FloatField(default=0.0)),
                ('nursing_rs', models.FloatField(default=0.0)),
                ('other_charge', models.FloatField(default=0.0)),
                ('other_rs', models.FloatField(default=0.0)),
                ('total_rs', models.FloatField(default=0.0)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnosis.diagnosismodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
                ('patient_opd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel')),
            ],
            options={
                'db_table': 'patient_billing',
            },
        ),
    ]
