# Generated by Django 3.2.9 on 2022-03-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0003_alter_patientbillingmodel_procedure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbillingmodel',
            name='discharge_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientbillingmodel',
            name='admission_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
