# Generated by Django 3.2.9 on 2022-03-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0004_auto_20220314_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbillingmodel',
            name='admission_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientbillingmodel',
            name='admission_date',
            field=models.DateTimeField(null=True),
        ),
    ]
