# Generated by Django 3.2.9 on 2022-03-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0006_patientbillingmodel_ot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbillingmodel',
            name='admission_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientbillingmodel',
            name='discharge_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientbillingmodel',
            name='ot_date',
            field=models.DateField(null=True),
        ),
    ]
