# Generated by Django 3.2.9 on 2022-04-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0007_auto_20220315_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientbillingmodel',
            old_name='operative_charge_rs',
            new_name='procedure_charge',
        ),
    ]
