# Generated by Django 3.2.9 on 2022-04-27 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_billing', '0008_rename_operative_charge_rs_patientbillingmodel_procedure_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbillingmodel',
            name='procedure_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_procedure_name', to='manage_fields.managefieldsmodel'),
        ),
    ]
