# Generated by Django 3.2.9 on 2022-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0009_alter_patientbillingmodel_procedure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbillingmodel',
            name='other_charge',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
