# Generated by Django 3.2.9 on 2022-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0010_alter_patientbillingmodel_other_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbillingmodel',
            name='room_type',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
