# Generated by Django 3.2.9 on 2022-06-28 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0012_alter_patientbillingmodel_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbillingmodel',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
