# Generated by Django 3.2.9 on 2022-08-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0014_auto_20220704_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbillingmodel',
            name='payment',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('CASH', 'CASH'), ('CHECK', 'CHECK')], default='CASH', max_length=15),
        ),
    ]
