# Generated by Django 3.2.9 on 2022-09-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0015_patientbillingmodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbillingmodel',
            name='payment',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('CASH', 'CASH'), ('CHEQUE', 'CHEQUE')], default='CASH', max_length=15),
        ),
    ]
