# Generated by Django 3.2.9 on 2023-03-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_billing', '0016_alter_patientbillingmodel_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbillingmodel',
            name='cheque_no',
            field=models.IntegerField(default=0),
        ),
    ]
