# Generated by Django 3.2.9 on 2021-12-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='diagnosis_id',
            new_name='diagnosisId',
        ),
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='diagnosis_name',
            new_name='diagnosisName',
        ),
        migrations.RemoveField(
            model_name='diagnosismodel',
            name='medicine',
        ),
    ]
