# Generated by Django 3.2.9 on 2021-12-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20211226_1905'),
        ('diagnosis', '0002_auto_20211226_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosismodel',
            name='medicine',
            field=models.ManyToManyField(to='medicine.MedicineModel'),
        ),
    ]
