# Generated by Django 3.2.9 on 2021-12-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_diagnosismodel_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='diagnosisId',
            new_name='diagnosis_id',
        ),
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='diagnosisName',
            new_name='diagnosis_name',
        ),
    ]
