# Generated by Django 3.2.9 on 2022-03-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_diagnosismedicinemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosismodel',
            name='ut_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosismodel',
            name='ut_weeks',
            field=models.IntegerField(null=True),
        ),
    ]
