# Generated by Django 3.2.9 on 2022-03-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_auto_20220316_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosismodel',
            name='diagnosis_name',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
