# Generated by Django 3.2.9 on 2022-03-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_alter_diagnosismodel_diagnosis_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosismodel',
            name='advice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
