# Generated by Django 3.2.9 on 2022-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0008_diagnosismodel_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosismodel',
            name='diagnosis_type',
            field=models.CharField(default='D', max_length=3),
        ),
    ]
