# Generated by Django 3.2.9 on 2022-07-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0010_alter_diagnosismodel_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='ut_days',
            new_name='fu',
        ),
    ]
