# Generated by Django 3.2.9 on 2022-03-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_mtp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmtpmodel',
            name='reason_for_mtp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reason_for_mtp', to='manage_fields.managefieldsmodel'),
        ),
    ]
