# Generated by Django 3.2.9 on 2022-03-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mtp', '0003_patientmtpmodel_termination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmtpmodel',
            name='discharge_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
