# Generated by Django 3.2.9 on 2022-03-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mtp', '0005_auto_20220315_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmtpmodel',
            name='admission_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientmtpmodel',
            name='procedure_date',
            field=models.DateField(null=True),
        ),
    ]
