# Generated by Django 3.2.9 on 2022-06-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mtp', '0007_alter_patientmtpmodel_reason_for_mtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmtpmodel',
            name='religion',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patientmtpmodel',
            name='ut_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
