# Generated by Django 3.2.9 on 2022-06-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0006_fieldmastermodel_slug'),
        ('patient_mtp', '0008_auto_20220624_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmtpmodel',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mtp_religion', to='manage_fields.managefieldsmodel'),
        ),
    ]
