# Generated by Django 3.2.9 on 2022-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mtp', '0009_alter_patientmtpmodel_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmtpmodel',
            name='live_male_female',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
