# Generated by Django 3.2.9 on 2022-01-24 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0005_diagnosismedicinemodel'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPrescriptionModel',
            fields=[
                ('patient_prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.consultationmodel')),
                ('diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnosis.diagnosismodel')),
            ],
            options={
                'db_table': 'patient_prescription',
            },
        ),
    ]
