# Generated by Django 3.2.9 on 2022-01-20 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0004_remove_patientmodel_pid'),
        ('advice', '0003_auto_20220118_1527'),
        ('diagnosis', '0005_diagnosismedicinemodel'),
        ('manage_fields', '0004_auto_20220117_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationModel',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('parity', models.CharField(choices=[('PRIMI', 'PRIMI'), ('MULTI', 'MUTLI')], default='PRIMI', max_length=15)),
                ('prev_del_type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('CESAREAN', 'CESAREAN')], default='NORMAL', max_length=15)),
                ('present_history', models.CharField(default='', max_length=250)),
                ('past_history', models.CharField(default='', max_length=250)),
                ('family_history', models.CharField(default='', max_length=250)),
                ('opd_date', models.DateField(default=django.utils.timezone.now)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('lmp_date', models.DateField(default=django.utils.timezone.now)),
                ('edd_date', models.DateField(default=django.utils.timezone.now)),
                ('ftnd_male_live', models.IntegerField(default=0)),
                ('ftnd_male_dead', models.IntegerField(default=0)),
                ('ftnd_female_live', models.IntegerField(default=0)),
                ('ftnd_female_dead', models.IntegerField(default=0)),
                ('ftlscs_male_live', models.IntegerField(default=0)),
                ('ftlscs_male_dead', models.IntegerField(default=0)),
                ('ftlscs_female_live', models.IntegerField(default=0)),
                ('ftlscs_female_dead', models.IntegerField(default=0)),
                ('possible_lmp', models.DateField(default=django.utils.timezone.now)),
                ('possible_edd', models.DateField(default=django.utils.timezone.now)),
                ('pa_gyn', models.BooleanField(default=False)),
                ('pa_obs', models.BooleanField(default=False)),
                ('fu', models.IntegerField(null=True)),
                ('fu_date', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.TextField(null=True)),
                ('hb', models.CharField(default='', max_length=50)),
                ('tsh', models.CharField(default='', max_length=50)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advice.advicemodel')),
                ('blood_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blood_group', to='manage_fields.managefieldsmodel')),
                ('bp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bp', to='manage_fields.managefieldsmodel')),
                ('breast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='breast', to='manage_fields.managefieldsmodel')),
                ('co', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co', to='manage_fields.managefieldsmodel')),
                ('cvs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cvs', to='manage_fields.managefieldsmodel')),
                ('diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnosis.diagnosismodel')),
                ('hbsag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hbsag', to='manage_fields.managefieldsmodel')),
                ('hiv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hiv', to='manage_fields.managefieldsmodel')),
                ('ho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ho', to='manage_fields.managefieldsmodel')),
                ('lcterus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lcterus', to='manage_fields.managefieldsmodel')),
                ('oedema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oedema', to='manage_fields.managefieldsmodel')),
                ('pallor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pallor', to='manage_fields.managefieldsmodel')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
                ('puls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='puls', to='manage_fields.managefieldsmodel')),
                ('pv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pv', to='manage_fields.managefieldsmodel')),
                ('resperistion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resperistion', to='manage_fields.managefieldsmodel')),
                ('rs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rs', to='manage_fields.managefieldsmodel')),
                ('spo2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spo2', to='manage_fields.managefieldsmodel')),
                ('temprature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temprature', to='manage_fields.managefieldsmodel')),
                ('tt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tt', to='manage_fields.managefieldsmodel')),
                ('urine_protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='urine_protein', to='manage_fields.managefieldsmodel')),
                ('urine_sugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='urine_sugar', to='manage_fields.managefieldsmodel')),
                ('vdrl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vdrl', to='manage_fields.managefieldsmodel')),
            ],
            options={
                'db_table': 'consultation',
            },
        ),
    ]
