# Generated by Django 3.2.9 on 2022-01-27 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0001_initial'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmodel',
            name='patient_opd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel'),
        ),
    ]
