# Generated by Django 3.2.9 on 2022-02-27 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultationmodel_patient_opd'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmodel',
            name='no_of_femaile',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='no_of_male',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ftlscs_female_dead',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ftlscs_female_live',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ftlscs_male_dead',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ftlscs_male_live',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ftnd_female_dead',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ftnd_female_live',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ftnd_male_dead',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ftnd_male_live',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='fu_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='hb',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='pa_gyn',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='pa_obs',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='possible_edd',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='possible_lmp',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='tsh',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
