# Generated by Django 3.2.9 on 2022-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_auto_20220227_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='prev_del_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('CAESAREAN', 'CAESAREAN')], default='NORMAL', max_length=15),
        ),
    ]
