# Generated by Django 3.2.9 on 2022-03-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('consultation', '0005_alter_consultationmodel_prev_del_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmodel',
            name='eb_pp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eb_pp', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='fhs',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='ps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ps', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='ut',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='ut_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='ut_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='advice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advice', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='blood_group',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='bp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='breast',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='co',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='cvs',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='fu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fu', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='hbsag',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='hiv',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ho',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='lcterus',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='oedema',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='pallor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='parity',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='prev_del_type',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='puls',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='resperistion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='rs',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='spo2',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='temprature',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='tsh',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='tt',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='urine_protein',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='urine_sugar',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='vdrl',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
