# Generated by Django 3.2.9 on 2022-03-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_auto_20220302_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationmodel',
            old_name='no_of_femaile',
            new_name='no_of_female',
        ),
    ]
