# Generated by Django 3.2.9 on 2022-04-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_consultationmodel_pa_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='tt',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
