# Generated by Django 3.2.9 on 2022-04-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_alter_consultationmodel_tt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationmodel',
            name='tt',
        ),
    ]
