# Generated by Django 3.2.9 on 2022-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_remove_consultationmodel_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmodel',
            name='other',
            field=models.TextField(null=True),
        ),
    ]
