# Generated by Django 3.2.9 on 2022-04-16 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_consultationmodel_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='advice',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='breast',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='co',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='cvs',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='edd_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='family_history',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='fhs',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ho',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='lcterus',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='lmp_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='oedema',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='opd_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='pa_value',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='pallor',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='parity',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='past_history',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='present_history',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='prev_del_type',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='regd_no',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='rs',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='temprature',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ut',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ut_days',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ut_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
