# Generated by Django 3.2.9 on 2022-05-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0005_alter_managefieldsmodel_field_value'),
        ('consultation', '0013_auto_20220506_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationmodel',
            name='department',
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='co',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='hb',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='ho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ho', to='manage_fields.managefieldsmodel'),
        ),
    ]
