# Generated by Django 3.2.9 on 2022-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0014_auto_20220506_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='spo2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmodel',
            name='tsh',
            field=models.FloatField(default=0, null=True),
        ),
    ]
