# Generated by Django 3.2.9 on 2022-05-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0016_alter_consultationmodel_resperistion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='resperistion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
