# Generated by Django 3.2.9 on 2022-06-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0006_alter_patientopdmodel_status'),
        ('consultation', '0017_alter_consultationmodel_resperistion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='patient_opd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel'),
        ),
    ]
