# Generated by Django 3.2.9 on 2022-07-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0018_alter_consultationmodel_patient_opd'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmodel',
            name='married_life',
            field=models.IntegerField(default=0),
        ),
    ]
