# Generated by Django 3.2.9 on 2022-07-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0006_fieldmastermodel_slug'),
        ('consultation', '0019_consultationmodel_married_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='breast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='breast', to='manage_fields.managefieldsmodel'),
        ),
    ]
