# Generated by Django 3.2.9 on 2022-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0021_auto_20220711_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='patient_detail',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL')], default='PARTIAL', max_length=8, null=True),
        ),
    ]
