# Generated by Django 3.2.9 on 2022-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0023_alter_consultationmodel_patient_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='patient_detail',
            field=models.CharField(default='', max_length=8, null=True),
        ),
    ]
