# Generated by Django 3.2.9 on 2022-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0025_alter_consultationmodel_patient_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationmodel',
            old_name='bp',
            new_name='daistolic_bp',
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='systolic_bp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
