# Generated by Django 3.2.9 on 2021-12-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statemodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='statemodel',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='statemodel',
            old_name='state_id',
            new_name='stateId',
        ),
        migrations.RenameField(
            model_name='statemodel',
            old_name='state_name',
            new_name='stateName',
        ),
    ]
