# Generated by Django 3.2.9 on 2021-12-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20211226_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statemodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='statemodel',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='statemodel',
            old_name='stateId',
            new_name='state_id',
        ),
        migrations.RenameField(
            model_name='statemodel',
            old_name='stateName',
            new_name='state_name',
        ),
    ]
