# Generated by Django 3.2.9 on 2022-06-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_auto_20211228_1610'),
        ('state', '0003_auto_20211228_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemodel',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='language.languagemodel'),
        ),
    ]
