# Generated by Django 3.2.9 on 2022-02-05 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0007_rename_husband_name_patientmodel_husband_father_name'),
        ('patient_opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientUSGReportModel',
            fields=[
                ('patient_usgreport_id', models.AutoField(primary_key=True, serialize=False)),
                ('regd_no', models.CharField(default='', max_length=100)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('no_of_foetus', models.IntegerField(default=0)),
                ('cardiac_activity', models.CharField(default='', max_length=100)),
                ('presentation', models.TextField(null=True)),
                ('ga_weeks', models.IntegerField(default=0)),
                ('ga_day', models.IntegerField(default=0)),
                ('ga_edd', models.IntegerField(default=0)),
                ('crl_weeks', models.IntegerField(default=0)),
                ('crl_day', models.IntegerField(default=0)),
                ('crl_edd', models.IntegerField(default=0)),
                ('fl_weeks', models.IntegerField(default=0)),
                ('fl_day', models.IntegerField(default=0)),
                ('fl_edd', models.IntegerField(default=0)),
                ('bpd_weeks', models.IntegerField(default=0)),
                ('bpd_day', models.IntegerField(default=0)),
                ('bpd_edd', models.IntegerField(default=0)),
                ('hc_weeks', models.IntegerField(default=0)),
                ('hc_day', models.IntegerField(default=0)),
                ('hc_edd', models.IntegerField(default=0)),
                ('ac_weeks', models.IntegerField(default=0)),
                ('ac_day', models.IntegerField(default=0)),
                ('ac_edd', models.IntegerField(default=0)),
                ('avg_weeks', models.IntegerField(default=0)),
                ('avg_day', models.IntegerField(default=0)),
                ('avg_edd', models.IntegerField(default=0)),
                ('possible_lmp', models.CharField(default='', max_length=100)),
                ('placental_location', models.CharField(default='', max_length=100)),
                ('amount_of_liquor', models.CharField(default='', max_length=100)),
                ('anomalies', models.CharField(default='', max_length=250)),
                ('remark', models.TextField(null=True)),
                ('usg_report', models.TextField(null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientmodel')),
                ('patient_opd', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel')),
            ],
            options={
                'db_table': 'patient_usgreport',
            },
        ),
    ]
