# Generated by Django 3.2.9 on 2022-03-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_usgreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='anomalies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anomalies', to='manage_fields.managefieldsmodel'),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='no_of_foetus',
            field=models.CharField(default='', max_length=25),
        ),
    ]
