# Generated by Django 3.2.9 on 2022-03-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_fields', '0004_auto_20220117_1601'),
        ('patient_usgreport', '0002_auto_20220302_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='placental_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='placental_location', to='manage_fields.managefieldsmodel'),
        ),
    ]
