# Generated by Django 3.2.9 on 2022-03-15 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgreport', '0003_alter_patientusgreportmodel_placental_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='ac_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='ac_edd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='ac_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='amount_of_liquor',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='avg_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='avg_edd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='avg_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='bpd_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='bpd_edd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='bpd_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='cardiac_activity',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='crl_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='crl_edd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='crl_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='fl_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='fl_edd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='fl_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='ga_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='ga_edd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='ga_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='hc_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='hc_edd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='hc_weeks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='no_of_foetus',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='possible_lmp',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
