# Generated by Django 3.2.9 on 2022-03-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgreport', '0004_auto_20220315_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientusgreportmodel',
            name='ac_edd',
        ),
        migrations.RemoveField(
            model_name='patientusgreportmodel',
            name='avg_edd',
        ),
        migrations.RemoveField(
            model_name='patientusgreportmodel',
            name='bpd_edd',
        ),
        migrations.RemoveField(
            model_name='patientusgreportmodel',
            name='crl_edd',
        ),
        migrations.RemoveField(
            model_name='patientusgreportmodel',
            name='fl_edd',
        ),
        migrations.RemoveField(
            model_name='patientusgreportmodel',
            name='ga_edd',
        ),
        migrations.RemoveField(
            model_name='patientusgreportmodel',
            name='hc_edd',
        ),
    ]
