# Generated by Django 3.2.9 on 2022-03-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_usgreport', '0005_auto_20220315_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientusgreportmodel',
            name='ac_edd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientusgreportmodel',
            name='avg_edd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientusgreportmodel',
            name='bpd_edd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientusgreportmodel',
            name='crl_edd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientusgreportmodel',
            name='fl_edd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientusgreportmodel',
            name='ga_edd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientusgreportmodel',
            name='hc_edd',
            field=models.DateField(null=True),
        ),
    ]
