# Generated by Django 3.2.9 on 2022-06-03 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_opd', '0006_alter_patientopdmodel_status'),
        ('patient_usgreport', '0006_auto_20220315_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusgreportmodel',
            name='patient_opd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_opd.patientopdmodel'),
        ),
    ]
